### ISSUE TITLE
Padding right in form fields for error / succes states

### ISSUE THREAD

**Issue by javierarques** [peertransfer/flystyles#32]
![pasted image at 2017_08_31 12_34 pm](https://user-images.githubusercontent.com/1564123/29919312-1f09d8ac-8e49-11e7-8cf3-05f7f9e788aa.png)

**Comment by javierarques** [comment]
![pasted image at 2017_08_31 12_34 pm](https://user-images.githubusercontent.com/1564123/29919338-31e9c702-8e49-11e7-8e32-57f6c6609f95.png)

**Comment by javierarques** [comment]
![pasted image at 2017_08_31 12_37 pm](https://user-images.githubusercontent.com/1564123/29919346-3e723004-8e49-11e7-94a5-b3aa3c36217f.png)

**Comment by demipel8** [comment]
Not an issue right now
