### ISSUE TITLE
Form hint should dissapear correctly

### ISSUE THREAD

**Issue by salvafc** [peertransfer/flystyles#35]
Hints in forms are appearing from behind the form in a nice and animated way, would be ideal if hint should disappear with an animation as well and not suddenly when they lose focus. Same as they appear but backward. Here's a gif explaining it better.

![forms_hint](https://user-images.githubusercontent.com/4070773/33369761-d8bce972-d4f5-11e7-8619-d4ddff8fe0c2.gif)

**Comment by demipel8** [comment]
Already implemented in flystyles
