### ISSUE TITLE
Change size and color of Prefix

### ISSUE THREAD

**Issue by salvafc** [peertransfer/flystyles#36]
Prefix changes:  
- Shouldn't have background color
- Font size should be 14px
- Should have color: #38495B;

![captura de pantalla 2017-11-29 a las 13 33 38](https://user-images.githubusercontent.com/4070773/33375799-63944738-d50b-11e7-9406-92fe204c124a.png)

**Comment by demipel8** [comment]
Already implemented in flystyles
