### ISSUE TITLE
Remove vertical line of Sufix

### ISSUE THREAD

**Issue by salvafc** [peertransfer/flystyles#37]
Remove vertical line of sufix, also, shouldn't have background color and font size should be 14px with #38495B color.

Here's an example of it:

![captura de pantalla 2017-11-29 a las 13 33 38](https://user-images.githubusercontent.com/4070773/33375833-850535c6-d50b-11e7-9063-bbf273d70c81.png)

**Comment by demipel8** [comment]
Same as #36
