### ISSUE TITLE
Next button animation in Firefox

### ISSUE THREAD

**Issue by omoreno** [peertransfer/flystyles#39]
Seems in Firefox the arrow is going beyond the size of the button and then it puts the ... instead of the animation.
![next](https://user-images.githubusercontent.com/235576/34413356-2ff437c8-ebe3-11e7-8b91-5010221a68a1.gif)

**Comment by demipel8** [comment]
Seems fixed in current version

![nextfirefox](https://user-images.githubusercontent.com/4971724/45283572-8f04dc80-b4de-11e8-84b5-0516ccf259af.gif)
